---
- name: Install ruby-full ruby-bundler build-essential
  hosts: all
  tasks:
    - name: Install the packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ruby-full
        - ruby-bundler
        - build-essential                                                                                                                    l